
package View;


public class Gerente_GUI extends javax.swing.JFrame {

    public Gerente_GUI() {
        initComponents();
        analisar_btn.setVisible(false);
        Cadastrar_btn.setVisible(false);
        nome1_lbl.setVisible(false);
        nome2_lbl.setVisible(false);
        email1_lbl.setVisible(false);
        email2_lbl.setVisible(false);
        id1_lbl.setVisible(false);
        id2_lbl.setVisible(false);
        voltarmenu_btn.setVisible(true);
        voltar_btn.setVisible(false);
        sair_btn.setVisible(true);
        analisar_btn.setVisible(true);
        Cadastrar_btn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo_lbl = new javax.swing.JLabel();
        subtitulo2_lbl = new javax.swing.JLabel();
        pessoal_btn = new javax.swing.JButton();
        Cadastrar_btn = new javax.swing.JButton();
        analisar_btn = new javax.swing.JButton();
        nome1_lbl = new javax.swing.JLabel();
        email1_lbl = new javax.swing.JLabel();
        id1_lbl = new javax.swing.JLabel();
        voltarmenu_btn = new javax.swing.JButton();
        sair_btn = new javax.swing.JButton();
        voltar_btn = new javax.swing.JButton();
        nome2_lbl = new javax.swing.JLabel();
        email2_lbl = new javax.swing.JLabel();
        id2_lbl = new javax.swing.JLabel();
        subtitulo_lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(82, 148, 177));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\2ESPF\\java\\aula1\\GsJava\\src\\Image\\logoGsJava.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 10, 140, 120);

        titulo_lbl.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        titulo_lbl.setText("Tech Naut Rivers");
        jPanel1.add(titulo_lbl);
        titulo_lbl.setBounds(180, 10, 210, 34);

        subtitulo2_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        subtitulo2_lbl.setText("Central do Gerente");
        jPanel1.add(subtitulo2_lbl);
        subtitulo2_lbl.setBounds(210, 80, 130, 30);

        pessoal_btn.setText("Informações pessoais");
        pessoal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoal_btnActionPerformed(evt);
            }
        });
        jPanel1.add(pessoal_btn);
        pessoal_btn.setBounds(180, 120, 180, 23);

        Cadastrar_btn.setText("Cadastrar Pesquisador");
        Cadastrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Cadastrar_btn);
        Cadastrar_btn.setBounds(310, 170, 190, 23);

        analisar_btn.setText("Analisar pesquisadores");
        analisar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analisar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(analisar_btn);
        analisar_btn.setBounds(40, 170, 180, 23);

        nome1_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nome1_lbl.setText("NOME:");
        jPanel1.add(nome1_lbl);
        nome1_lbl.setBounds(60, 200, 60, 30);

        email1_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email1_lbl.setText("E-MAIL: ");
        jPanel1.add(email1_lbl);
        email1_lbl.setBounds(60, 240, 70, 20);

        id1_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id1_lbl.setText("IDgerente:");
        jPanel1.add(id1_lbl);
        id1_lbl.setBounds(60, 280, 70, 20);

        voltarmenu_btn.setText("VOLTAR");
        voltarmenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarmenu_btnActionPerformed(evt);
            }
        });
        jPanel1.add(voltarmenu_btn);
        voltarmenu_btn.setBounds(0, 343, 90, 20);

        sair_btn.setText("SAIR");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sair_btn);
        sair_btn.setBounds(460, 340, 70, 20);

        voltar_btn.setText("VOLTAR");
        voltar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(voltar_btn);
        voltar_btn.setBounds(370, 340, 90, 20);
        jPanel1.add(nome2_lbl);
        nome2_lbl.setBounds(170, 200, 170, 30);
        jPanel1.add(email2_lbl);
        email2_lbl.setBounds(170, 240, 180, 20);
        jPanel1.add(id2_lbl);
        id2_lbl.setBounds(170, 280, 20, 20);

        subtitulo_lbl1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        subtitulo_lbl1.setText("Navegando rumo a oceanos mais limpos.");
        jPanel1.add(subtitulo_lbl1);
        subtitulo_lbl1.setBounds(180, 50, 210, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(525, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pessoal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoal_btnActionPerformed
        Model.FuncoesGerente_DAO.informacoes();
    }//GEN-LAST:event_pessoal_btnActionPerformed

    private void voltarmenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarmenu_btnActionPerformed
        Model.FuncoesGerente_DAO.voltarmenu(Gerente_GUI.this);
    }//GEN-LAST:event_voltarmenu_btnActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        Model.FuncoesGerente_DAO.fechar();
    }//GEN-LAST:event_sair_btnActionPerformed

    private void voltar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_btnActionPerformed
        Model.FuncoesGerente_DAO.voltar();
    }//GEN-LAST:event_voltar_btnActionPerformed

    private void Cadastrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_btnActionPerformed
        Model.FuncoesGerente_DAO.cadastrar(Gerente_GUI.this);
    }//GEN-LAST:event_Cadastrar_btnActionPerformed

    private void analisar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analisar_btnActionPerformed
        Model.FuncoesGerente_DAO.analisar(Gerente_GUI.this);
    }//GEN-LAST:event_analisar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerente_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Cadastrar_btn;
    public static javax.swing.JButton analisar_btn;
    public static javax.swing.JLabel email1_lbl;
    public static javax.swing.JLabel email2_lbl;
    public static javax.swing.JLabel id1_lbl;
    public static javax.swing.JLabel id2_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel nome1_lbl;
    public static javax.swing.JLabel nome2_lbl;
    public static javax.swing.JButton pessoal_btn;
    public static javax.swing.JButton sair_btn;
    public static javax.swing.JLabel subtitulo2_lbl;
    public static javax.swing.JLabel subtitulo_lbl1;
    public static javax.swing.JLabel titulo_lbl;
    public static javax.swing.JButton voltar_btn;
    public static javax.swing.JButton voltarmenu_btn;
    // End of variables declaration//GEN-END:variables
}
