
package View;

public class Pesquisador_GUI extends javax.swing.JFrame {

   
    public Pesquisador_GUI() {
        initComponents();
        titulo_lbl.setVisible(true);
        subtitulo_lbl.setVisible(true);
        subtitulo2_lbl.setVisible(true);
        nome1_lbl.setVisible(false);
        nome2_lbl.setVisible(false);
        local1_lbl.setVisible(false);
        local2_lbl.setVisible(false);
        email1_lbl.setVisible(false);
        email2_lbl.setVisible(false);
        id1_lbl.setVisible(false);
        id2_lbl.setVisible(false);
        relatorio1_lbl.setVisible(false);
        relatorio2_lbl.setVisible(false);
        voltar_btn.setVisible(false);
        voltarmenu_btn.setVisible(true);
        subtextorelatorio_lbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo_lbl = new javax.swing.JLabel();
        subtitulo_lbl = new javax.swing.JLabel();
        subtitulo2_lbl = new javax.swing.JLabel();
        realizar_btn = new javax.swing.JButton();
        analisar_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pessoal_btn = new javax.swing.JButton();
        nome1_lbl = new javax.swing.JLabel();
        nome2_lbl = new javax.swing.JLabel();
        local1_lbl = new javax.swing.JLabel();
        email1_lbl = new javax.swing.JLabel();
        id1_lbl = new javax.swing.JLabel();
        local2_lbl = new javax.swing.JLabel();
        email2_lbl = new javax.swing.JLabel();
        id2_lbl = new javax.swing.JLabel();
        relatorio1_lbl = new javax.swing.JLabel();
        relatorio2_lbl = new javax.swing.JLabel();
        voltar_btn = new javax.swing.JButton();
        voltarmenu_btn = new javax.swing.JButton();
        subtextorelatorio_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(82, 148, 177));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\2ESPF\\java\\aula1\\GsJava\\src\\Image\\logoGsJava.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 10, 140, 120);

        titulo_lbl.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        titulo_lbl.setText("Tech Naut Rivers");
        jPanel1.add(titulo_lbl);
        titulo_lbl.setBounds(180, 10, 210, 34);

        subtitulo_lbl.setText("Navegando rumo a oceanos mais limpos.");
        jPanel1.add(subtitulo_lbl);
        subtitulo_lbl.setBounds(200, 50, 230, 14);

        subtitulo2_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        subtitulo2_lbl.setText("Central do Pesquisador");
        jPanel1.add(subtitulo2_lbl);
        subtitulo2_lbl.setBounds(200, 90, 150, 30);

        realizar_btn.setText("Realizar relatório");
        realizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(realizar_btn);
        realizar_btn.setBounds(330, 160, 140, 23);

        analisar_btn.setText("Analisar sensores");
        analisar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analisar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(analisar_btn);
        analisar_btn.setBounds(70, 160, 150, 23);

        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 340, 70, 20);

        pessoal_btn.setText("Informações pessoais");
        pessoal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoal_btnActionPerformed(evt);
            }
        });
        jPanel1.add(pessoal_btn);
        pessoal_btn.setBounds(190, 120, 180, 23);

        nome1_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nome1_lbl.setText("NOME:");
        jPanel1.add(nome1_lbl);
        nome1_lbl.setBounds(60, 180, 60, 30);
        jPanel1.add(nome2_lbl);
        nome2_lbl.setBounds(130, 180, 170, 30);

        local1_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        local1_lbl.setText("LOCAL:");
        jPanel1.add(local1_lbl);
        local1_lbl.setBounds(60, 210, 50, 30);

        email1_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email1_lbl.setText("E-MAIL: ");
        jPanel1.add(email1_lbl);
        email1_lbl.setBounds(60, 250, 60, 20);

        id1_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id1_lbl.setText("      IDpesquisador:");
        jPanel1.add(id1_lbl);
        id1_lbl.setBounds(0, 280, 120, 20);
        jPanel1.add(local2_lbl);
        local2_lbl.setBounds(130, 210, 170, 30);
        jPanel1.add(email2_lbl);
        email2_lbl.setBounds(130, 250, 180, 20);
        jPanel1.add(id2_lbl);
        id2_lbl.setBounds(130, 280, 130, 20);

        relatorio1_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        relatorio1_lbl.setText("Último relatório realizado:");
        jPanel1.add(relatorio1_lbl);
        relatorio1_lbl.setBounds(300, 180, 160, 30);

        relatorio2_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatorio2_lblMouseClicked(evt);
            }
        });
        jPanel1.add(relatorio2_lbl);
        relatorio2_lbl.setBounds(300, 250, 160, 30);

        voltar_btn.setText("VOLTAR");
        voltar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(voltar_btn);
        voltar_btn.setBounds(370, 340, 90, 20);

        voltarmenu_btn.setText("VOLTAR");
        voltarmenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarmenu_btnActionPerformed(evt);
            }
        });
        jPanel1.add(voltarmenu_btn);
        voltarmenu_btn.setBounds(0, 343, 90, 20);

        subtextorelatorio_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subtextorelatorio_lbl.setText("Clique nele para visualizar melhor!");
        jPanel1.add(subtextorelatorio_lbl);
        subtextorelatorio_lbl.setBounds(300, 210, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(525, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pessoal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoal_btnActionPerformed
        Model.FuncoesPesquisador_DAO.informacoes();
    }//GEN-LAST:event_pessoal_btnActionPerformed

    private void analisar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analisar_btnActionPerformed
        Model.FuncoesPesquisador_DAO.sensor(Pesquisador_GUI.this);
    }//GEN-LAST:event_analisar_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Model.FuncoesPesquisador_DAO.fechar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void voltar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_btnActionPerformed
        Model.FuncoesPesquisador_DAO.voltar();
    }//GEN-LAST:event_voltar_btnActionPerformed

    private void voltarmenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarmenu_btnActionPerformed
        Model.FuncoesPesquisador_DAO.voltarmenu(Pesquisador_GUI.this);
    }//GEN-LAST:event_voltarmenu_btnActionPerformed

    private void realizar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizar_btnActionPerformed
        Model.FuncoesPesquisador_DAO.relatorios(Pesquisador_GUI.this);
    }//GEN-LAST:event_realizar_btnActionPerformed

    private void relatorio2_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatorio2_lblMouseClicked
        Model.FuncoesPesquisador_DAO.mostrarelatorio();
    }//GEN-LAST:event_relatorio2_lblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisador_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton analisar_btn;
    public static javax.swing.JLabel email1_lbl;
    public static javax.swing.JLabel email2_lbl;
    public static javax.swing.JLabel id1_lbl;
    public static javax.swing.JLabel id2_lbl;
    public static javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel local1_lbl;
    public static javax.swing.JLabel local2_lbl;
    public static javax.swing.JLabel nome1_lbl;
    public static javax.swing.JLabel nome2_lbl;
    public static javax.swing.JButton pessoal_btn;
    public static javax.swing.JButton realizar_btn;
    public static javax.swing.JLabel relatorio1_lbl;
    public static javax.swing.JLabel relatorio2_lbl;
    public static javax.swing.JLabel subtextorelatorio_lbl;
    public static javax.swing.JLabel subtitulo2_lbl;
    public static javax.swing.JLabel subtitulo_lbl;
    public static javax.swing.JLabel titulo_lbl;
    public static javax.swing.JButton voltar_btn;
    public static javax.swing.JButton voltarmenu_btn;
    // End of variables declaration//GEN-END:variables
}
