
package View;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


public class Relatorio_GUI extends javax.swing.JFrame {

    
    public Relatorio_GUI() {
        initComponents();
        
        Model.FuncoesRelatorio_DAO.nome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_chooser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nivel_txt = new javax.swing.JTextField();
        conteudo_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        titulo_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        voltarPesquisador_btn = new javax.swing.JButton();
        data_lbl = new javax.swing.JLabel();
        idautor_txt = new javax.swing.JLabel();
        autor_txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        data_chooser.setBackground(new java.awt.Color(82, 148, 177));
        data_chooser.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Página de relatório");
        data_chooser.add(jLabel1);
        jLabel1.setBounds(140, 10, 250, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Autor:");
        data_chooser.add(jLabel2);
        jLabel2.setBounds(40, 80, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("IDautor:");
        data_chooser.add(jLabel3);
        jLabel3.setBounds(20, 110, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Data emissão:");
        data_chooser.add(jLabel4);
        jLabel4.setBounds(10, 140, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nível de Alerta:");
        data_chooser.add(jLabel5);
        jLabel5.setBounds(0, 170, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Conteúdo:");
        data_chooser.add(jLabel6);
        jLabel6.setBounds(10, 200, 80, 15);
        data_chooser.add(nivel_txt);
        nivel_txt.setBounds(100, 170, 240, 20);
        data_chooser.add(conteudo_txt);
        conteudo_txt.setBounds(20, 230, 490, 90);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Título:");
        data_chooser.add(jLabel7);
        jLabel7.setBounds(40, 50, 60, 20);
        data_chooser.add(titulo_txt);
        titulo_txt.setBounds(100, 50, 240, 20);

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        data_chooser.add(jButton1);
        jButton1.setBounds(450, 340, 80, 20);

        voltarPesquisador_btn.setText("VOLTAR");
        voltarPesquisador_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarPesquisador_btnActionPerformed(evt);
            }
        });
        data_chooser.add(voltarPesquisador_btn);
        voltarPesquisador_btn.setBounds(0, 343, 90, 20);
        data_chooser.add(data_lbl);
        data_lbl.setBounds(100, 140, 240, 20);
        data_chooser.add(idautor_txt);
        idautor_txt.setBounds(100, 110, 240, 20);
        data_chooser.add(autor_txt);
        autor_txt.setBounds(100, 80, 240, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(data_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(data_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(525, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarPesquisador_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarPesquisador_btnActionPerformed
        Model.FuncoesRelatorio_DAO.voltapesquisador(Relatorio_GUI.this);
    }//GEN-LAST:event_voltarPesquisador_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Model.FuncoesRelatorio_DAO.enviar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel autor_txt;
    public static javax.swing.JTextField conteudo_txt;
    private javax.swing.JPanel data_chooser;
    public static javax.swing.JLabel data_lbl;
    public static javax.swing.JLabel idautor_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JTextField nivel_txt;
    public static javax.swing.JTextField titulo_txt;
    private javax.swing.JButton voltarPesquisador_btn;
    // End of variables declaration//GEN-END:variables
}
