
package View;


public class Sensor_GUI extends javax.swing.JFrame {

    public Sensor_GUI() {
        initComponents();
        oxigenio_btn.setVisible(true);
        salinidade_btn.setVisible(true);
        ph_btn.setVisible(true);
        oxigenio_lbl.setVisible(false);
        oxigenio2_lbl.setVisible(false);
        oxigenio3_lbl.setVisible(false);
        oxigenio4_lbl.setVisible(false);
        oxigenio5_lbl.setVisible(false);
        salinidade_lbl.setVisible(false);
        salinidade2_lbl.setVisible(false);
        salinidade3_lbl.setVisible(false);
        salinidade4_lbl.setVisible(false);
        salinidade5_lbl.setVisible(false);
        ph_lbl.setVisible(false);
        ph2_lbl.setVisible(false);
        ph3_lbl.setVisible(false);
        ph4_lbl.setVisible(false);
        ph5_lbl.setVisible(false);
        realizar_btn.setVisible(true);
        voltarPesquisador_btn.setVisible(true);
        mediaoxi_lbl.setVisible(false);
        mediaph_lbl.setVisible(false);
        mediasal_lbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        oxigenio_btn = new javax.swing.JButton();
        salinidade_btn = new javax.swing.JButton();
        ph_btn = new javax.swing.JButton();
        oxigenio_lbl = new javax.swing.JLabel();
        salinidade_lbl = new javax.swing.JLabel();
        salinidade2_lbl = new javax.swing.JLabel();
        oxigenio2_lbl = new javax.swing.JLabel();
        salinidade3_lbl = new javax.swing.JLabel();
        salinidade4_lbl = new javax.swing.JLabel();
        ph_lbl = new javax.swing.JLabel();
        ph2_lbl = new javax.swing.JLabel();
        ph3_lbl = new javax.swing.JLabel();
        oxigenio3_lbl = new javax.swing.JLabel();
        oxigenio4_lbl = new javax.swing.JLabel();
        ph4_lbl = new javax.swing.JLabel();
        oxigenio5_lbl = new javax.swing.JLabel();
        salinidade5_lbl = new javax.swing.JLabel();
        ph5_lbl = new javax.swing.JLabel();
        voltarPesquisador_btn = new javax.swing.JButton();
        realizar_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mediaoxi_lbl = new javax.swing.JLabel();
        mediasal_lbl = new javax.swing.JLabel();
        mediaph_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(82, 148, 177));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Menu dos sensores");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 230, 34);

        oxigenio_btn.setText("Oxigênio");
        oxigenio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oxigenio_btnActionPerformed(evt);
            }
        });
        jPanel1.add(oxigenio_btn);
        oxigenio_btn.setBounds(60, 100, 90, 23);

        salinidade_btn.setText("Salinidade");
        salinidade_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salinidade_btnActionPerformed(evt);
            }
        });
        jPanel1.add(salinidade_btn);
        salinidade_btn.setBounds(210, 100, 100, 23);

        ph_btn.setText("Ph");
        ph_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ph_btnActionPerformed(evt);
            }
        });
        jPanel1.add(ph_btn);
        ph_btn.setBounds(380, 100, 100, 23);
        jPanel1.add(oxigenio_lbl);
        oxigenio_lbl.setBounds(70, 130, 60, 20);
        jPanel1.add(salinidade_lbl);
        salinidade_lbl.setBounds(230, 130, 70, 20);
        jPanel1.add(salinidade2_lbl);
        salinidade2_lbl.setBounds(230, 160, 70, 20);
        jPanel1.add(oxigenio2_lbl);
        oxigenio2_lbl.setBounds(70, 160, 60, 20);
        jPanel1.add(salinidade3_lbl);
        salinidade3_lbl.setBounds(230, 190, 70, 20);
        jPanel1.add(salinidade4_lbl);
        salinidade4_lbl.setBounds(230, 220, 70, 20);
        jPanel1.add(ph_lbl);
        ph_lbl.setBounds(400, 130, 70, 20);
        jPanel1.add(ph2_lbl);
        ph2_lbl.setBounds(400, 160, 70, 20);
        jPanel1.add(ph3_lbl);
        ph3_lbl.setBounds(400, 190, 70, 20);
        jPanel1.add(oxigenio3_lbl);
        oxigenio3_lbl.setBounds(70, 190, 60, 20);
        jPanel1.add(oxigenio4_lbl);
        oxigenio4_lbl.setBounds(70, 220, 60, 20);
        jPanel1.add(ph4_lbl);
        ph4_lbl.setBounds(400, 220, 70, 20);
        jPanel1.add(oxigenio5_lbl);
        oxigenio5_lbl.setBounds(70, 250, 60, 20);
        jPanel1.add(salinidade5_lbl);
        salinidade5_lbl.setBounds(230, 250, 70, 20);
        jPanel1.add(ph5_lbl);
        ph5_lbl.setBounds(400, 250, 70, 20);

        voltarPesquisador_btn.setText("VOLTAR");
        voltarPesquisador_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarPesquisador_btnActionPerformed(evt);
            }
        });
        jPanel1.add(voltarPesquisador_btn);
        voltarPesquisador_btn.setBounds(0, 343, 100, 20);

        realizar_btn.setText("Realizar relatório");
        realizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(realizar_btn);
        realizar_btn.setBounds(390, 340, 140, 23);

        jLabel2.setText("Últimas 5 leituras");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 50, 110, 14);
        jPanel1.add(mediaoxi_lbl);
        mediaoxi_lbl.setBounds(70, 300, 90, 20);
        jPanel1.add(mediasal_lbl);
        mediasal_lbl.setBounds(230, 300, 110, 20);
        jPanel1.add(mediaph_lbl);
        mediaph_lbl.setBounds(400, 300, 90, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(525, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void realizar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizar_btnActionPerformed
       Model.FuncoesSensor_DAO.relatorios(Sensor_GUI.this);
    }//GEN-LAST:event_realizar_btnActionPerformed

    private void oxigenio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oxigenio_btnActionPerformed
        Model.FuncoesSensor_DAO.oxigenio();
    }//GEN-LAST:event_oxigenio_btnActionPerformed

    private void voltarPesquisador_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarPesquisador_btnActionPerformed
        Model.FuncoesSensor_DAO.voltarpesquisador(Sensor_GUI.this);
    }//GEN-LAST:event_voltarPesquisador_btnActionPerformed

    private void salinidade_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salinidade_btnActionPerformed
        Model.FuncoesSensor_DAO.salinidade();
    }//GEN-LAST:event_salinidade_btnActionPerformed

    private void ph_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ph_btnActionPerformed
        Model.FuncoesSensor_DAO.ph();
    }//GEN-LAST:event_ph_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sensor_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sensor_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sensor_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sensor_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sensor_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel mediaoxi_lbl;
    public static javax.swing.JLabel mediaph_lbl;
    public static javax.swing.JLabel mediasal_lbl;
    public static javax.swing.JLabel oxigenio2_lbl;
    public static javax.swing.JLabel oxigenio3_lbl;
    public static javax.swing.JLabel oxigenio4_lbl;
    public static javax.swing.JLabel oxigenio5_lbl;
    public static javax.swing.JButton oxigenio_btn;
    public static javax.swing.JLabel oxigenio_lbl;
    public static javax.swing.JLabel ph2_lbl;
    public static javax.swing.JLabel ph3_lbl;
    public static javax.swing.JLabel ph4_lbl;
    public static javax.swing.JLabel ph5_lbl;
    public static javax.swing.JButton ph_btn;
    public static javax.swing.JLabel ph_lbl;
    public static javax.swing.JButton realizar_btn;
    public static javax.swing.JLabel salinidade2_lbl;
    public static javax.swing.JLabel salinidade3_lbl;
    public static javax.swing.JLabel salinidade4_lbl;
    public static javax.swing.JLabel salinidade5_lbl;
    public static javax.swing.JButton salinidade_btn;
    public static javax.swing.JLabel salinidade_lbl;
    private javax.swing.JButton voltarPesquisador_btn;
    // End of variables declaration//GEN-END:variables
}
